- hosts: webservers
  become: true
  become_user: "{{ ansible_ssh_user }}"

  vars_prompt:
  
  - name: env_file_location
    prompt: "enter local path to the .env file"
    private: false

  tasks:

  - name: "apt update"
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: "install nginx"
    apt:
      name: ['nginx']
      state: latest

  - name: copy nginx configuration file
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/sites-enabled/default
      owner: root
      group: root
      mode: '0644'
    notify: restart nginx
    
  - name: download node 14 package
    get_url:
      url: https://deb.nodesource.com/setup_14.x
      dest: "/home/adminos/installnode.sh"
      mode: 0755

  - name: install downloaded node 14 package
    shell: "{{ home_dir }}/installnode.sh && rm {{ home_dir }}/installnode.sh"

  - name: "download and install build-essential package (supporting nodejs)"
    apt:
      name: ['build-essential']
      state: latest

  - name: "download and install nodejs dependencies"
    apt:
      name: ['nodejs']
      state: latest

  - name: "download and install pm2 package globally"
    npm:
      name: pm2
      global: yes

  - name: download the weight tracking app from the github repository
    git:
        repo: https://github.com/sagia91/bootcamp-app.git
        dest: "{{ home_dir }}/bootcamp-app/"

  - name: download and install weight tracking app dependencies
    npm:
      path: "{{ home_dir }}/bootcamp-app/"

  - name: copy .env file
    template:
      src: "{{ env_file_location }}"
      dest: "{{ home_dir }}/bootcamp-app/.env"
      owner: root
      group: root
      mode: '0644'

  - name: run db init script
    command: "npm run initdb"
    run_once: true
    args:
      chdir: "{{ home_dir }}/bootcamp-app/"

  - name: make pm2 load at startup
    shell: "sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u {{ ansible_ssh_user }} --hp {{ home_dir }}"

  - name: run the app (using pm2)
    command: pm2 start .
    args:
      chdir: "{{ home_dir }}/bootcamp-app/"

  - name: reload pm2 processes
    command: pm2 reload all
    environment:
      PATH: /home/ubuntu/.nvm/versions/node/v12.10.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted